//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIGSHOPE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bigshopeEntities : DbContext
    {
        public bigshopeEntities()
            : base("name=bigshopeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBrand> tblBrands { get; set; }
        public virtual DbSet<tblGen> tblGens { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
        public virtual DbSet<tblProcessor> tblProcessors { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
    
        public virtual int addProducts(string name, string desc, string price, string img, Nullable<int> qnty, string ram, Nullable<int> brand, Nullable<int> process, Nullable<int> gen)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var priceParameter = price != null ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            var qntyParameter = qnty.HasValue ?
                new ObjectParameter("qnty", qnty) :
                new ObjectParameter("qnty", typeof(int));
    
            var ramParameter = ram != null ?
                new ObjectParameter("ram", ram) :
                new ObjectParameter("ram", typeof(string));
    
            var brandParameter = brand.HasValue ?
                new ObjectParameter("brand", brand) :
                new ObjectParameter("brand", typeof(int));
    
            var processParameter = process.HasValue ?
                new ObjectParameter("process", process) :
                new ObjectParameter("process", typeof(int));
    
            var genParameter = gen.HasValue ?
                new ObjectParameter("gen", gen) :
                new ObjectParameter("gen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addProducts", nameParameter, descParameter, priceParameter, imgParameter, qntyParameter, ramParameter, brandParameter, processParameter, genParameter);
        }
    
        public virtual ObjectResult<adminLogin_Result> adminLogin(string adminName, string adminPassword)
        {
            var adminNameParameter = adminName != null ?
                new ObjectParameter("adminName", adminName) :
                new ObjectParameter("adminName", typeof(string));
    
            var adminPasswordParameter = adminPassword != null ?
                new ObjectParameter("adminPassword", adminPassword) :
                new ObjectParameter("adminPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<adminLogin_Result>("adminLogin", adminNameParameter, adminPasswordParameter);
        }
    
        public virtual ObjectResult<showBrands_Result> showBrands()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showBrands_Result>("showBrands");
        }
    
        public virtual ObjectResult<showGen_Result> showGen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showGen_Result>("showGen");
        }
    
        public virtual ObjectResult<showProcessor_Result> showProcessor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showProcessor_Result>("showProcessor");
        }
    
        public virtual ObjectResult<showProducts_Result> showProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showProducts_Result>("showProducts");
        }
    
        public virtual int deleteProduct(Nullable<int> prdID)
        {
            var prdIDParameter = prdID.HasValue ?
                new ObjectParameter("prdID", prdID) :
                new ObjectParameter("prdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteProduct", prdIDParameter);
        }
    
        public virtual int deleteBrnd(Nullable<int> brndid)
        {
            var brndidParameter = brndid.HasValue ?
                new ObjectParameter("brndid", brndid) :
                new ObjectParameter("brndid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteBrnd", brndidParameter);
        }
    
        public virtual int deleteGen(Nullable<int> genId)
        {
            var genIdParameter = genId.HasValue ?
                new ObjectParameter("genId", genId) :
                new ObjectParameter("genId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteGen", genIdParameter);
        }
    
        public virtual int deleteProc(Nullable<int> procId)
        {
            var procIdParameter = procId.HasValue ?
                new ObjectParameter("procId", procId) :
                new ObjectParameter("procId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteProc", procIdParameter);
        }
    
        public virtual ObjectResult<loginUser_Result> loginUser(string usermail, string userpass)
        {
            var usermailParameter = usermail != null ?
                new ObjectParameter("usermail", usermail) :
                new ObjectParameter("usermail", typeof(string));
    
            var userpassParameter = userpass != null ?
                new ObjectParameter("userpass", userpass) :
                new ObjectParameter("userpass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<loginUser_Result>("loginUser", usermailParameter, userpassParameter);
        }
    
        public virtual int regUser(string userfirst, string usersecond, string usermail, string userpass)
        {
            var userfirstParameter = userfirst != null ?
                new ObjectParameter("userfirst", userfirst) :
                new ObjectParameter("userfirst", typeof(string));
    
            var usersecondParameter = usersecond != null ?
                new ObjectParameter("usersecond", usersecond) :
                new ObjectParameter("usersecond", typeof(string));
    
            var usermailParameter = usermail != null ?
                new ObjectParameter("usermail", usermail) :
                new ObjectParameter("usermail", typeof(string));
    
            var userpassParameter = userpass != null ?
                new ObjectParameter("userpass", userpass) :
                new ObjectParameter("userpass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("regUser", userfirstParameter, usersecondParameter, usermailParameter, userpassParameter);
        }
    
        public virtual int addBrands(string brndName, string brndDesc)
        {
            var brndNameParameter = brndName != null ?
                new ObjectParameter("brndName", brndName) :
                new ObjectParameter("brndName", typeof(string));
    
            var brndDescParameter = brndDesc != null ?
                new ObjectParameter("brndDesc", brndDesc) :
                new ObjectParameter("brndDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addBrands", brndNameParameter, brndDescParameter);
        }
    
        public virtual int addGenration(string genName, string genDesc)
        {
            var genNameParameter = genName != null ?
                new ObjectParameter("genName", genName) :
                new ObjectParameter("genName", typeof(string));
    
            var genDescParameter = genDesc != null ?
                new ObjectParameter("genDesc", genDesc) :
                new ObjectParameter("genDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addGenration", genNameParameter, genDescParameter);
        }
    
        public virtual int addProc(string procName, string procDesc)
        {
            var procNameParameter = procName != null ?
                new ObjectParameter("procName", procName) :
                new ObjectParameter("procName", typeof(string));
    
            var procDescParameter = procDesc != null ?
                new ObjectParameter("procDesc", procDesc) :
                new ObjectParameter("procDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addProc", procNameParameter, procDescParameter);
        }
    
        public virtual ObjectResult<showClients_Result> showClients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showClients_Result>("showClients");
        }
    
        public virtual int deleteClients(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteClients", idParameter);
        }
    
        [DbFunction("bigshopeEntities", "fn_Split")]
        public virtual IQueryable<fn_Split_Result> fn_Split(string text, string delimiter)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Split_Result>("[bigshopeEntities].[fn_Split](@text, @delimiter)", textParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<showProdDetails_Result> showProdDetails(Nullable<int> prodID)
        {
            var prodIDParameter = prodID.HasValue ?
                new ObjectParameter("prodID", prodID) :
                new ObjectParameter("prodID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showProdDetails_Result>("showProdDetails", prodIDParameter);
        }
    
        public virtual int addClient(string name, string surname, string email, string phone, string address, string city, string state, string zip, string password, string stripeid)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("surname", surname) :
                new ObjectParameter("surname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var stripeidParameter = stripeid != null ?
                new ObjectParameter("stripeid", stripeid) :
                new ObjectParameter("stripeid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addClient", nameParameter, surnameParameter, emailParameter, phoneParameter, addressParameter, cityParameter, stateParameter, zipParameter, passwordParameter, stripeidParameter);
        }
    
        public virtual ObjectResult<loginClient_Result> loginClient(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<loginClient_Result>("loginClient", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<addToCart_Result> addToCart(string itemList)
        {
            var itemListParameter = itemList != null ?
                new ObjectParameter("itemList", itemList) :
                new ObjectParameter("itemList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<addToCart_Result>("addToCart", itemListParameter);
        }
    
        public virtual ObjectResult<showCustomers_Result> showCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showCustomers_Result>("showCustomers");
        }
    
        public virtual int deleteCustomer(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteCustomer", idParameter);
        }
    
        public virtual ObjectResult<loginCustomer_Result> loginCustomer(string email, string pass)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<loginCustomer_Result>("loginCustomer", emailParameter, passParameter);
        }
    
        public virtual int regCustomer(string name, string surname, string email, string phone, string address, string city, string state, string zip, string password, string stripeid)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("surname", surname) :
                new ObjectParameter("surname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var stripeidParameter = stripeid != null ?
                new ObjectParameter("stripeid", stripeid) :
                new ObjectParameter("stripeid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("regCustomer", nameParameter, surnameParameter, emailParameter, phoneParameter, addressParameter, cityParameter, stateParameter, zipParameter, passwordParameter, stripeidParameter);
        }
    
        public virtual ObjectResult<showPrdByBrnds_Result> showPrdByBrnds(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showPrdByBrnds_Result>("showPrdByBrnds", idParameter);
        }
    
        public virtual ObjectResult<showProdByBrnds_Result> showProdByBrnds(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showProdByBrnds_Result>("showProdByBrnds", idParameter);
        }
    
        public virtual ObjectResult<showProdByGen_Result> showProdByGen(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showProdByGen_Result>("showProdByGen", idParameter);
        }
    
        public virtual ObjectResult<showProdByProc_Result> showProdByProc(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showProdByProc_Result>("showProdByProc", idParameter);
        }
    
        public virtual ObjectResult<searchProduct_Result> searchProduct(string prodName)
        {
            var prodNameParameter = prodName != null ?
                new ObjectParameter("prodName", prodName) :
                new ObjectParameter("prodName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchProduct_Result>("searchProduct", prodNameParameter);
        }
    
        public virtual ObjectResult<searchProducts_Result> searchProducts(string prodName)
        {
            var prodNameParameter = prodName != null ?
                new ObjectParameter("prodName", prodName) :
                new ObjectParameter("prodName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchProducts_Result>("searchProducts", prodNameParameter);
        }
    
        public virtual ObjectResult<getOrder_Result> getOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getOrder_Result>("getOrder");
        }
    }
}
