//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIGSHOPE
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string customer_surname { get; set; }
        public string customer_email { get; set; }
        public string customer_phone { get; set; }
        public string customer_address { get; set; }
        public string customer_city { get; set; }
        public string customer_state { get; set; }
        public int customer_zip { get; set; }
        public string customer_password { get; set; }
        public string customer_stripe_id { get; set; }
    }
}
